name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6 
  flutter_animate: ^4.2.0
  mongo_dart: ^0.9.0
  bson: ^4.0.0

  # Firebase (optional)
  firebase_core: ^2.21.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.0

  # State Management
  provider: ^6.1.1

  # Local Storage (optional)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true